import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./Contexts/UserContext";
import Navbar from "./CommonCode/UiCode/Navbar";
import Providers from "./provider";
import CaptchaProvider from "./CommonCode/auth/captchaProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Note we actually don't need any order context
  // hence remove <OrderProvider>
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className="z-0">
            <CaptchaProvider>
              <Navbar />
              <UserProvider>
                {children}
              </UserProvider>
            </CaptchaProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
